language: node_js
cache:
  directories:
    - node_modules
before_install:
  - git config --global user.name "sixertoy"
  - git config --global user.email "sixertoy.github@gmail.com"
script:
  - npm run deploy
